// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using planner_web_api.Infrastructure.Context;

namespace planner_web_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220208232958_adicao_subject_table_and_dependencies")]
    partial class adicao_subject_table_and_dependencies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("backend.Domain.entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("projectId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("projectId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("planner_web_api.Domain.entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("backend.Domain.entities.Subject", b =>
                {
                    b.HasOne("planner_web_api.Domain.entities.Project", "project")
                        .WithMany("Subjects")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("project");
                });

            modelBuilder.Entity("planner_web_api.Domain.entities.Project", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
